### PR TITLE
Fixing issue #38 Adding documentation for Scatter.py file

### PR DESCRIPTION
**Pull request by misherwa**
This Pull Request is for #38. Used ChatGPT to add documentation to the first two functions  "github_auth" and "weeksToDate". This should help to better understand how the function works.

ChatGPT link: https://chatgpt.com/share/6702f2e3-98c4-800c-b234-46b5e96e55b7

### CODE REVIEW

**Comment by thecatfour** [comment]
I would recommend specifying the datatypes for the parameters in addition to your added documentation. For example, github_auth() currently shows the following:

Screenshot 2024-10-06 220610

You can add datatypes to the function parameters like this:

Screenshot 2024-10-06 221017

This helps documentation as it gives a simple summary of what data the function expects as shown below:

Screenshot 2024-10-06 220958

**Comment by misherwa** [comment]
Thanks for the recommendation. 

Do you also have a review of this PR using ChatGPT to provide additional insight? I think it's required for the Lab homework. 

But I think you can double check with ChatGPT about your recommendation and put a link to the conversation.

**Comment by thecatfour** [comment]
I believe ChatGPT is not required for reviews. He said so in the discord.


Regardless, here is ChatGPT's take on specifying datatypes for parameters for Python fuctions. It agrees that it improves clarity and reduces ambiguity.

ChatGPT: https://chatgpt.com/share/6704308b-db28-8004-96f7-08f6fb2ec325

**Comment by misherwa** [comment]
Ohh gotcha, thanks

**Pull request merged**
